---
- name: sub | Create document root directories
  ansible.builtin.file:
    path: "{{ item_site['document_root'] }}"
    state: directory
    owner: www-data
    group: www-data
    mode: "0755"
  loop: "{{ sites }}"
  loop_control:
    loop_var: item_site
  tags:
    - deploy
- name: sub | Deploy test environment content
  ansible.builtin.copy:
    src: files/default/test/index.html
    dest: "{{ item_site['document_root'] }}/index.html"
    owner: www-data
    group: www-data
    mode: "0644"
    state: present # noqa: R114
  when: item_site['name'] == 'test' # noqa: L039
  loop: "{{ sites }}"
  loop_control:
    loop_var: item_site
  tags:
    - deploy
- name: sub | Deploy CI/CD environment content
  ansible.builtin.copy:
    src: files/default/ci/index.html
    dest: "{{ item_site['document_root'] }}/index.html"
    owner: www-data
    group: www-data
    mode: "0644"
    state: present # noqa: R114
  when: item_site['name'] == 'ci'
  loop: "{{ sites }}"
  loop_control:
    loop_var: item_site
  tags:
    - deploy
- name: sub | Deploy status environment content
  ansible.builtin.copy:
    src: files/default/status/index.html
    dest: "{{ item_site['document_root'] }}/index.html"
    owner: www-data
    group: www-data
    mode: "0644"
    state: present # noqa: R114
  when: item_site['name'] == 'status'
  loop: "{{ sites }}"
  loop_control:
    loop_var: item_site
  tags:
    - deploy
