---
- name: Install nginx packages
  ansible.builtin.package:
    name: "{{ nginx_packages[ansible_facts['os_family']] }}"
    state: present
  when: nginx_packages[ansible_facts['os_family']] is defined
  tags:
    - install

- name: fail2ban | Install fail2ban packages
  ansible.builtin.package:
    name: "{{ fail2ban_packages[ansible_facts['os_family']] }}"
    state: present
  when: fail2ban_packages[ansible_facts['os_family']] is defined
  tags:
    - install
- name: ssl | Install SSL packages
  ansible.builtin.package:
    name: "{{ ssl_packages[ansible_facts['os_family']] }}"
    state: present
  when: ssl_packages[ansible_facts['os_family']] is defined
  tags:
    - install
