---
- name: Install nginx packages
  ansible.builtin.package:
    name: "{{ nginx_packages[ansible_facts['os_family']] }}"
    state: present
  when: ansible_facts['os_family'] in nginx_packages

- name: Create nginx configuration directories
  ansible.builtin.file:
    path: "{{ item_dir }}"
    state: directory
    mode: "0755"
  loop:
    - /etc/nginx
    - /etc/nginx/conf.d
    - /etc/nginx/sites-available
    - /etc/nginx/sites-enabled
  loop_control:
    loop_var: item_dir # noqa: var-naming[no-role-prefix]
- name: sub | Deploy nginx main configuration
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    mode: "0644"
    validate: nginx -t -c %s
  notify: reload nginx
- name: sub | Deploy nginx security configuration
  ansible.builtin.template:
    src: security.conf.j2
    dest: /etc/nginx/conf.d/security.conf
    mode: "0644"
  notify: reload nginx
- name: Sub | Create document root directories
  ansible.builtin.file:
    path: "{{ item_site['document_root'] }}"
    state: directory
    owner: www-data
    group: www-data
    mode: "0755"
  loop: "{{ sites }}"
  loop_control:
    loop_var: item_site
  when: item_site is defined
- name: sub | Deploy static index.html files
  ansible.builtin.copy:
    src: "files/{{ item_site['name'] }}/index.html"
    dest: "{{ item_site['document_root'] }}/index.html"
    owner: www-data
    group: www-data
    mode: "0644"
    state: present # noqa: R114
  when: item_site['name'] in document_root_content
  loop: "{{ sites }}"
  loop_control:
    loop_var: item_site
  vars:
    item_site: "{{ item_site }}"
- name: sub | Remove default site configuration
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
    mode: "0644"
- name: sub | Start and enable nginx
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: true
