---
- name: sub | Install UFW
  ansible.builtin.package:
    name: ufw
    state: present
  when: ufw_enabled | bool
  tags:
    - ufw
- name: sub | Set UFW default policy
  ansible.builtin.command:
    cmd: ufw default {{ ufw_default_policy }} incoming
  when: ufw_enabled | bool
  changed_when: false
  tags:
    - ufw
  # noqa: R101
- name: sub | Configure UFW rules
  ansible.builtin.command:
    cmd: ufw allow {{ item_rule['port'] }}/tcp comment '{{ item_rule['comment'] }}'
  when: ufw_enabled | bool
  changed_when: false
  loop: "{{ ufw_rules }}"
  loop_control:
    loop_var: item_rule
  tags:
    - ufw
- name: sub | Enable UFW
  ansible.builtin.command:
    cmd: ufw --force enable
  when: ufw_enabled | bool
  changed_when: false
  tags:
    - ufw
